## CLASSIFICATION PROBLEM 

In [1]:
# make a binary class dataset 
from sklearn.datasets import make_classification

In [2]:
x , y = make_classification(n_samples=1000,
                    n_features=3 ,
                    n_classes=2,
                    n_redundant=1,
                    random_state=999)

In [3]:
x #indoendet feature 

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [4]:
y # deoendednt feature -> output 

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,

In [6]:
# train test split 
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test  = train_test_split(x,y,test_size=0.20,random_state=42)

In [7]:
# k neighbour classifier 

In [9]:
from sklearn.neighbors import KNeighborsClassifier

# model create 
classifier = KNeighborsClassifier(n_neighbors=5,weights='distance',algorithm='auto',p=2)

# traine the model 
classifier.fit(x_train,y_train)

# predict 
y_test_pred = classifier.predict(x_test)

In [10]:
# acuuracy check 
from sklearn.metrics import accuracy_score , confusion_matrix,classification_report

print(accuracy_score(y_test,y_test_pred))

print(confusion_matrix(y_test,y_test_pred))

print(classification_report(y_test,y_test_pred))

0.91
[[97  6]
 [12 85]]
              precision    recall  f1-score   support

           0       0.89      0.94      0.92       103
           1       0.93      0.88      0.90        97

    accuracy                           0.91       200
   macro avg       0.91      0.91      0.91       200
weighted avg       0.91      0.91      0.91       200



In [ ]:
KNeighborsClassifier()

In [11]:
# hyperparqametre tuning 

parameter = {
             'n_neighbors' :[3,4,5,6,7,8,9,10],
             'weights' :['uniform', 'distance'],
             'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],
             'p':[1,2]
            }

In [13]:
from sklearn.model_selection import GridSearchCV

# model creation 
clf = GridSearchCV(classifier,param_grid=parameter,scoring='accuracy',verbose=3,cv=3)

clf.fit(x_train,y_train)

Fitting 3 folds for each of 128 candidates, totalling 384 fits
[CV 1/3] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.899 total time=   0.0s
[CV 2/3] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.873 total time=   0.0s
[CV 3/3] END algorithm=auto, n_neighbors=3, p=1, weights=uniform;, score=0.898 total time=   0.0s
[CV 1/3] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.899 total time=   0.0s
[CV 2/3] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.873 total time=   0.0s
[CV 3/3] END algorithm=auto, n_neighbors=3, p=1, weights=distance;, score=0.891 total time=   0.0s
[CV 1/3] END algorithm=auto, n_neighbors=3, p=2, weights=uniform;, score=0.903 total time=   0.0s
[CV 2/3] END algorithm=auto, n_neighbors=3, p=2, weights=uniform;, score=0.876 total time=   0.0s
[CV 3/3] END algorithm=auto, n_neighbors=3, p=2, weights=uniform;, score=0.895 total time=   0.0s
[CV 1/3] END algorithm=auto, n_neighbors=3, p=2, wei

GridSearchCV(cv=3, estimator=KNeighborsClassifier(weights='distance'),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [3, 4, 5, 6, 7, 8, 9, 10], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=3)

In [14]:
# best parameter 
clf.best_params_

{'algorithm': 'auto', 'n_neighbors': 8, 'p': 2, 'weights': 'uniform'}

In [15]:
y_test_pred= clf.predict(x_test)

In [16]:
# acuuracy check 
from sklearn.metrics import accuracy_score , confusion_matrix,classification_report

print(accuracy_score(y_test,y_test_pred))

print(confusion_matrix(y_test,y_test_pred))

print(classification_report(y_test,y_test_pred))

0.92
[[98  5]
 [11 86]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.92       103
           1       0.95      0.89      0.91        97

    accuracy                           0.92       200
   macro avg       0.92      0.92      0.92       200
weighted avg       0.92      0.92      0.92       200



In [17]:
def scale_dwon(x_train,x_test):
    #model creatce\
    scaler = StanderdScaler()
    
    x_train_scaled = scaler.fit_transform(x_train)
    
    x_test_scaled=scaler.transform(x_test)
    
    return x_train_scaled,x_test_scaled

In [24]:
import numpy as np
x1 = 3 
y1 = 4
x2 = 5
y2 = 6

eucledian_distance = np.sqrt((x2-x1)**2+(y2-y1)**2)

eucledian_distance

2.8284271247461903

In [25]:
manhaten_dist = (x2-x1)+(y2-y1)
manhaten_dist

4